apiVersion: v1
kind: Service
metadata:
  name: {{ include "matete-ping-pong-ping.container" . }}
  labels:
    {{- include "matete-ping-pong-ping.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "matete-ping-pong.container.port" . }}
      protocol: TCP
      name: th
    - port: 80
      targetPort: {{ include "matete-ping-pong.container.port" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "matete-ping-pong.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "matete-ping-pong-pong.container" . }}
  labels:
    {{- include "matete-ping-pong-pong.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "matete-ping-pong.container.port" . }}
      protocol: TCP
      name: th
    - port: 80
      targetPort: {{ include "matete-ping-pong.container.port" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "matete-ping-pong-ping.selectorLabels" . | nindent 4 }}
