version: "3.3"
services: 
  pong: 
    build: ./Pong
    container_name: matete_pong_kafka
    environment:
        BROKER: "host.docker.internal:9092"  
    extra_hosts:
      - "host.docker.internal:host-gateway"    
    networks:
      - default-net
  ping: 
    build: ./Ping
    container_name: matete_ping_kafka
    environment:
        BROKER: "host.docker.internal:9092"  
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    networks:
      - default-net
networks:
  default-net:
    driver: bridge
#TODO: fix bug