version: "3.3"
services: 
  zookeeper:
    image: 'bitnami/zookeeper'
    container_name: zookeeper_server
    ports:
      - '12181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-app-tier

  kafka:
    image: 'bitnami/kafka'
    container_name: kafka_server
    ports:
      - '19092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

    networks:
      - kafka-app-tier


  pong: 
    build: ./Pong
    container_name: matete_pong_kafka
    environment:
        BROKER: "kafka:9092"  

    networks:
      - kafka-app-tier
    depends_on:
      - kafka

  ping: 
    build: ./Ping
    container_name: matete_ping_kafka
    environment:
        BROKER: "kafka:9092"  
    networks:
      - kafka-app-tier
    depends_on:
      - kafka

networks:
  kafka-app-tier:
    driver: bridge
