version: "3"
services: 
  pong: 
    build: ./Pong
    container_name: matete_pong_kafka
    ports: 
      - "9092:9092"
    environment:
        BROKER: ponglocalhost:9092   


  ping: 
    build: ./Ping
    container_name: matete_ping_kafka
    ports: 
      - "9092:9092"
    environment:
        BROKER: localhnjost:9092  
  
