# Default values for matete-ping-pong.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#pingpong parameters

# kafkaBroker: 
#   service:
#     ports:
#       client: 29092
#       external: 19094
#       internal: 19093
#   containerPorts:
#       client: 14095


mateteClientPortName: kafka-port
mateteClientContainerPort: 80


replicaCount: 1
ping:
  image:
    repository: jeromecondere/matete-ping
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
pong:
  image:
    repository: jeromecondere/matete-pong
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
kafka: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
   fsGroup: 1000


containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  

service:
  type: ClusterIP
  port: 422

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
